### PR TITLE
Make quotesmaker.py executable with like ./quotesmaker

### PR DESCRIPTION
**Pull request by lablnet**
Just have to do chmod +x quotesmaker.py
then it can be executed ./quotesmaker

In Linux + Mac systems

### CODE REVIEW

**Comment by adityagirinv** [comment]
After chmod +x quotesmaker.py
Run python quotesmaker.py -h

**Comment by Lablnet** [comment]
> After chmod +x quotesmaker.py
> Run python quotesmaker.py -h

yes but we do not have to give .py explicitly

just

./quotesmaker -h

**Comment by adityagirinv** [comment]
Well i dont know about that😢 how to do so..

**Comment by lablnet** [comment]
> Well i dont know about that how to do so..

oh you have button at button merge to master you can click that ! to any new PR

**Pull request closed without merging**
